version: '3.8'    
    
services:
  postgres:
    container_name: "postgres"
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pg-dump:/var/lib/postgresql/dump

volumes:
  postgres-data:

networks:
  default:
    name: infra

